import 'package:redditify/models/genre.dart';

List<Genre> subredditsList = [
  Genre(
    title: "Classical music",
    asset: "assets/images/classical-music.jpg",
    subreddits: [
      "composer",
      "baroque",
      "classicalmusic",
      "contemporary",
      "concertband",
      "choralmusic",
      "ChamberMusic",
      "EarlyMusic",
      "earlymusicalnotation",
      "ElitistClassical",
      "icm",
      "Opera",
      "orchestra"
    ],
  ),
  Genre(
    title: "Electronic music",
    asset: "assets/images/electronic-music.jpg",
    subreddits: [
      "acidhouse",
      "ambientmusic",
      "AStateOfTrance",
      "AtmosphericDnB",
      "BigBeat",
      "boogiemusic ",
      "breakbeat",
      "breakcore",
      "chicagohouse",
      "chillout",
      "Chipbreak",
      "Chiptunes",
      "complextro",
      "cxd ",
      "darkstep",
      "deephouse",
      "DnB",
      "DubStep",
      "EDM",
      "EBM ",
      "electronicdancemusic",
      "ElectronicJazz",
      "ElectronicBlues",
      "electrohiphop",
      "electrohouse",
      "electronicmagic",
      "ElectronicMusic",
      "electropop",
      "electroswing",
      "ExperimentalMusic",
      "fidget",
      "filth",
      "frenchelectro",
      "frenchhouse",
      "funkhouse",
      "fusiondancemusic",
      "futurebeats",
      "FutureFunkAirlines",
      "FutureGarage",
      "futuresynth",
      "gabber",
      "glitch",
      "glitchop",
      "Grime",
      "happyhardcore",
      "hardhouse",
      "hardstyle",
      "house",
      "idm",
      "industrialmusic",
      "ItaloDisco",
      "latinhouse",
      "LiquidDubstep",
      "mashups",
      "melodichouse",
      "minimal",
      "mixes",
      "moombahcore",
      "nightstep",
      "OldskoolRave ",
      "Outrun",
      "theOverload ",
      "partymusic",
      "plunderphonics",
      "psybient",
      "PsyBreaks",
      "psytrance",
      "purplemusic",
      "raggajungle",
      "RealDubstep",
      "skweee",
      "swinghouse",
      "tech_house",
      "Techno",
      "Trance",
      "tranceandbass ",
      "trap",
      "tribalbeats",
      "TropicalHouse",
      "ukfunky",
      "witchhouse",
      "wuuB"
    ],
  ),
  Genre(
    title: "Rock/Metal",
    asset: "assets/images/rock-music.jpg",
    subreddits: [
      "80sHardcorePunk",
      "90sAlternative",
      "90sPunk",
      "90sRock",
      "AlternativeRock",
      "AltCountry",
      "AORMelodic",
      "ausmetal ",
      "BlackMetal",
      "bluegrass",
      "Blues",
      "bluesrock",
      "Boneyard ",
      "CanadianClassicRock",
      "CanadianMusic",
      "ClassicRock",
      "country",
      "Christcore",
      "crunkcore",
      "deathcore",
      "deathmetal",
      "Djent",
      "DoomMetal",
      "Drone",
      "Emo",
      "EmoScreamo",
      "epicmetal",
      "flocked ",
      "folk",
      "folkmetal",
      "folkpunk",
      "folkrock",
      "folkunknown",
      "GaragePunk",
      "GothicMetal",
      "Grunge",
      "hardcore",
      "HardRock",
      "horrorpunk ",
      "indie_rock",
      "jrock",
      "krautrock",
      "LadiesofMetal",
      "MathRock",
      "melodicdeathmetal",
      "MelodicMetal",
      "MetalNews",
      "Metalmusic",
      "metal",
      "metalcore",
      "ModernRockMusic",
      "monsterfuzz",
      "neopsychedelia",
      "NewWave",
      "noiserock",
      "numetal",
      "pianorock",
      "poppunkers",
      "PostHardcore",
      "PostRock",
      "powermetal",
      "powerpop",
      "ProgMetal",
      "progrockmusic",
      "PsychedelicRock",
      "punk",
      "Punkskahardcore",
      "Punk_Rock",
      "raprock ",
      "Rock",
      "shoegaze",
      "stonerrock",
      "symphonicblackmetal",
      "symphonicmetal",
      "synthrock",
      "ThrowbackCore",
      "truethrash",
      "Truemetal",
      "OutlawCountry",
      "WomenRock"
    ],
  ),
  Genre(
    title: "Hip-Hop",
    asset: "assets/images/hip-hop-music.jpg",
    subreddits: [
      "80sHipHop",
      "90sHipHop",
      "altrap",
      "asianrap",
      "backpacker",
      "backspin",
      "BayRap",
      "ChapHop",
      "ChiefKeef ",
      "DrillandBop",
      "Emo_Trap",
      "Gfunk",
      "hiphopheads",
      "hiphopheadsnorthwest",
      "hiphop101",
      "MemphisRap",
      "NYrap",
      "Rap",
      "raprock ",
      "rapverses",
      "rhymesandbeats",
      "trapmuzik",
      "ukhiphopheads",
      "undergroundchicago",
      "LofiHipHop"
    ],
  ),
  Genre(
    title: "Decades",
    asset: "assets/images/decades-music.jpg",
    subreddits: [
      "2010smusic",
      "2000smusic",
      "90sMusic",
      "80sremixes",
      "80sMusic",
      "70sMusic",
      "60sMusic",
      "50sMusic"
    ],
  ),
  Genre(
    title: "By country/culture",
    asset: "assets/images/world-music.jpg",
    subreddits: [
      "AfricanMusic",
      "afrobeat",
      "balkanbrass",
      "balkanmusic",
      "brazilianmusic",
      "britpop",
      "CroatianMusic",
      "Flamenco",
      "Irishmusic",
      "ItalianMusic",
      "jpop ",
      "KoreanRock",
      "kpop ",
      "RoMusic ",
      "spop ",
      "somluso ",
      "UKbands",
      "WorldMusic"
    ],
  ),
  Genre(
    title: "Other",
    asset: "assets/images/other-music.jpg",
    subreddits: [
      "70s",
      "Acappella",
      "AcousticCovers",
      "ambientfolk",
      "animemusic",
      "BestOfDisney",
      "boomswing",
      "bossanova",
      "carmusic",
      "concerts",
      "chillmusic",
      "cpop",
      "Complextro",
      "dembow",
      "disco",
      "DreamPop",
      "dub",
      "Elephant6",
      "ETIMusic ",
      "Exotica",
      "FilmMusic",
      "FunkSouMusic",
      "gamemusic",
      "GamesMusicMixMash",
      "GunslingerMusic",
      "GypsyJazz",
      "IndieFolk",
      "jambands",
      "jazz",
      "JazzFusion",
      "JazzInfluence",
      "listentoconcerts",
      "klezmer",
      "lt10k ",
      "MedievalMusic",
      "MelancholyMusic",
      "minimalism_music",
      "motown",
      "MusicForConcentration",
      "muzyka",
      "NuDisco",
      "oldiemusic",
      "OldiesMusic ",
      "pianocovers",
      "PoptoRock",
      "QuietStorm",
      "rainymood",
      "recordstorefinds",
      "reggae",
      "remixxd ",
      "RetroMusic",
      "rnb",
      "rootsmusic",
      "SalsaMusic",
      "Ska",
      "Soca ",
      "songbooks",
      "Soulies",
      "SoulDivas",
      "SoundsVintage",
      "SpaceMusic",
      "SurfPunk",
      "swing",
      "Tango",
      "TheRealBookVideos",
      "TouhouMusic",
      "TraditionalMusic",
      "treemusic",
      "triphop",
      "vaporwave",
      "VintageObscura ",
      "vocaloid"
    ],
  )
];
